version: '2'

services:
  exploit:
    image: localhost:5000/team01/test-challenge
    depends_on:
      - challenge
      - flag-submit
  challenge:
    image: localhost:5000/test-challenge
    volumes:
      - "./flag:/flag"
    expose:
      - "8080"
  flag-submit:
    image: localhost:5000/flag-submit
    volumes:
      - "./submitflag:/flag"
    expose:
      - "1337"
